// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCvQoa21NHlmxVazHxuzd7LPRfUIbFPo',
    appId: '1:107503513510:web:5f36df26c9fcb64fc36967',
    messagingSenderId: '107503513510',
    projectId: 'bloc-quiz-flutter',
    authDomain: 'bloc-quiz-flutter.firebaseapp.com',
    storageBucket: 'bloc-quiz-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD26c9hUYWwOQfw8M2SXN-k5fZjxyuStG8',
    appId: '1:107503513510:android:25e3a16266a21e19c36967',
    messagingSenderId: '107503513510',
    projectId: 'bloc-quiz-flutter',
    storageBucket: 'bloc-quiz-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigomXY129-bjigqWf3TDHpYPxibuQdq8',
    appId: '1:107503513510:ios:dbcedcc17a110230c36967',
    messagingSenderId: '107503513510',
    projectId: 'bloc-quiz-flutter',
    storageBucket: 'bloc-quiz-flutter.appspot.com',
    iosBundleId: 'com.example.blockQuizApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCigomXY129-bjigqWf3TDHpYPxibuQdq8',
    appId: '1:107503513510:ios:a86fd8b6c4053636c36967',
    messagingSenderId: '107503513510',
    projectId: 'bloc-quiz-flutter',
    storageBucket: 'bloc-quiz-flutter.appspot.com',
    iosBundleId: 'com.example.blockQuizApp2.RunnerTests',
  );
}
