// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS6jQbd7OnQxVThiLTWAp4XSiNL28Ywkg',
    appId: '1:83910706782:web:7f8ae513786dd0a57496cf',
    messagingSenderId: '83910706782',
    projectId: 'testinglogin-6801e',
    authDomain: 'testinglogin-6801e.firebaseapp.com',
    storageBucket: 'testinglogin-6801e.appspot.com',
    measurementId: 'G-Y7FTPGQHTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9X1NWA4pthpNQ4z7_kBf2_zm0pBQc-8',
    appId: '1:83910706782:android:8c1bd436e12cdfab7496cf',
    messagingSenderId: '83910706782',
    projectId: 'testinglogin-6801e',
    storageBucket: 'testinglogin-6801e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0A6yvHbGC03dGNuaj0ozbi25nAmIjJC8',
    appId: '1:83910706782:ios:923d90a41e1478647496cf',
    messagingSenderId: '83910706782',
    projectId: 'testinglogin-6801e',
    storageBucket: 'testinglogin-6801e.appspot.com',
    iosBundleId: 'com.example.testSeriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0A6yvHbGC03dGNuaj0ozbi25nAmIjJC8',
    appId: '1:83910706782:ios:ee9b1d4a1142a9167496cf',
    messagingSenderId: '83910706782',
    projectId: 'testinglogin-6801e',
    storageBucket: 'testinglogin-6801e.appspot.com',
    iosBundleId: 'com.example.testSeriesApp.RunnerTests',
  );
}
