// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClrMCquRrITQuchCJPnbRmny2k3gd2FZs',
    appId: '1:13887453116:web:c4f03fabf1e67cd0fd5db9',
    messagingSenderId: '13887453116',
    projectId: 'myblocflutter',
    authDomain: 'myblocflutter.firebaseapp.com',
    databaseURL: 'https://myblocflutter-default-rtdb.firebaseio.com',
    storageBucket: 'myblocflutter.appspot.com',
    measurementId: 'G-RV5H3VY6C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHPL00FFiWA1AatMqKCopRsJAMTXK6zCI',
    appId: '1:13887453116:android:552a4c3a0f7d9413fd5db9',
    messagingSenderId: '13887453116',
    projectId: 'myblocflutter',
    databaseURL: 'https://myblocflutter-default-rtdb.firebaseio.com',
    storageBucket: 'myblocflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8BWOZcfZLmeHC067tqTr-avmCd-dnAYg',
    appId: '1:13887453116:ios:08ca4002b747b6dafd5db9',
    messagingSenderId: '13887453116',
    projectId: 'myblocflutter',
    databaseURL: 'https://myblocflutter-default-rtdb.firebaseio.com',
    storageBucket: 'myblocflutter.appspot.com',
    iosBundleId: 'com.example.testSeriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8BWOZcfZLmeHC067tqTr-avmCd-dnAYg',
    appId: '1:13887453116:ios:15e71746e61b1e8ffd5db9',
    messagingSenderId: '13887453116',
    projectId: 'myblocflutter',
    databaseURL: 'https://myblocflutter-default-rtdb.firebaseio.com',
    storageBucket: 'myblocflutter.appspot.com',
    iosBundleId: 'com.example.testSeriesApp.RunnerTests',
  );
}
